learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')), # 包含应用程序users定义的URL
    path('', include('learning_logs.urls')),
]
# 包括learning_logs.urls
# 包括users.urls

learning_logs/urls.py
"""定义learning_logs的URL模式"""

from django.urls import path  # 导入path 将URL映射到视图

from . import views  # 导入模块views 句点. 让python从当前urls.py 模块所在的文件夹导入views.py

app_name = 'learning_logs'  # 命名空间  name 属性指定别名
urlpatterns = [
	# 主页
	path('', views.index, name='index'),
	# 显示所有主题
	path('topics/', views.topics, name='topics'),
	# 特定主题的详细页面 在主页URL的字符串参数中添加topic/
	path('topics/<int:topic_id>/', views.topic, name='topic'),
	# 用于添加新主题的页面
	path('new_topic/', views.new_topic, name='new_topic'),
	# 用于添加新条目的页面
	path('net_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
	# 用于编辑条目的页面
	path('edit_entry/<int:entry_id>', views.edit_entry, name='edit_entry'),
]

# urlpatterns 是个列表，包含所有可在应用程序learning_logs中请求的页面
# URL模式就是对path()函数的调用 这个函数接受三个实参
"""
第一个是一个字符串，帮助Django正确的路由(route)请求。
收到请求的URL后，Django力图将请求路由给一个视图。
为此，它将搜索所有的URL模式，找到与当前请求匹配的那个。
Django忽略项目的基础URL(http://localhost:8000/)，
因此(‘‘)空字符串和基础的URL匹配，其他URL都与这个模式不匹配。
如果请求的URL与任何既有的URL都不匹配,Django将返回一个错误页面。
"""
"""
第二个实参指定了要调用views.py中的哪个函数。
请求的URL与前述正则表达式匹配时，Django将调用views.py中的函数index
"""
"""
第三个实参将这个URL模式的名称指定为index，让我们能在代码的其他地方引用它。
每当需要提供到这个主页链接时，都使用这个名称，而不是编写URL。
"""

users/urls.py
"""为应用程序users定义URL模式"""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
	# 包含默认的身份验证URL
	path('', include("django.contrib.auth.urls")),
	# 注册页面
	path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):  # 继承自Model
	"""用户学习的主题"""
	text = models.CharField(max_length=200)  # 属性text是由字符组成的数据 即文本（少量数据）
	date_added = models.DateTimeField(auto_now_add=True)  # 记录日期和时间的数据
	# 每当用户创建新主题时，Django会将这个属性自动设置为当前日期和时间

	owner = models.ForeignKey(User, on_delete=models.CASCADE)  # 建立外键关联

	def __str__(self):
		"""返回模型的字符串表示"""
		return self.text


class Entry(models.Model):
	"""学到的有关某个主题的具体知识"""
	topic = models.ForeignKey(Topic, on_delete=models.CASCADE)  # 外键实例 级联删除
	text = models.TextField()  # TextField实例  字段长度不受限制
	date_added = models.DateTimeField(auto_now_add=True)  # 按照创建顺序呈现条目，并在每个条目之间放置时间戳

	class Meta:  # 嵌套类 存储管理模型的额外信息
		verbose_name_plural = 'entries'

	def __str__(self):
		"""返回模型的字符串表示"""
		return f"{self.text[:30]}..."

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
#!/usr/bin/python3
# -*- coding: utf-8 -*-
# @Author  : fiuxiu
# @Time    : 2020年11月29日 17:29
# @Software: PyCharm
from django import forms

from .models import Topic, Entry


class TopicForm(forms.ModelForm):
	class Meta:
		model = Topic  # 根据模型Topic创建表单 其中只包含字段text
		fields = ['text']
		labels = {'text': ''}  # 让Django不要为字段text生成标签


class EntryForm(forms.ModelForm):
	class Meta:
		model = Entry
		fields = ['text']
		labels = {'text': ' '}
		widgets = {'text': forms.Textarea(attrs={'cols': 80})}   # 文本区域宽度80

learning_logs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Topic, Entry
from .forms import TopicForm, EntryForm


# 向对象request传递两个实参，request和一个可以用于创建页面的模板
# html本质是一个字符串，只不过浏览器认识它，可以将其解析成页面。
# 模板定义页面的外观，每当页面被请求时，Django将填入相关的数据。
# 模板能够让你访问视图提供的任何数据。
def index(request):  # 视图函数
	"""学习笔记的主页"""
	return render(request, 'learning_logs/index.html')


@login_required
def topics(request):
	"""显示所有的主题 处理URL匹配的页面的请求"""
	topics = Topic.objects.filter(owner=request.user).order_by('date_added') # 排序
	context = {'topics': topics}   # 定义上下文字典
	return render(request, 'learning_logs/topics.html', context)  # 第二个参数是模板（html）路径


@login_required
def topic(request, topic_id):
	"""显示单个主题及其所有的条目"""
	topic = Topic.objects.get(id=topic_id)
	# 确定请求的主题属于当前用户
	if topic.owner != request.user:
		raise Http404

	entries = topic.entry_set.order_by('-date_added')
	context = {'topic': topic, 'entries': entries}
	return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic(request):
	"""添加新主题"""
	if request.method != 'POST':
		# 未提交数据：创建一个新表单
		form = TopicForm()
	else:
		# POST提交数据：对数据进行处理
		form = TopicForm(data=request.POST)
		if form.is_valid():
			new_topic = form.save(commit=False)
			new_topic.owner = request.user
			new_topic.save()
			return redirect('learning_logs: topics')  # 重定向

	# 显示空表单或指出表单数据无效
	context = {'form': form}
	return render(request, 'learning_logs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
	"""在特定主题中添加新条目"""
	topic = Topic.objects.get(id=topic_id)

	if request.method != 'POST':
		# 未提交数据：创建一个新表单
		form = EntryForm()
	else:
		# POST提交数据：对数据进行处理
		form = EntryForm(data=request.POST)
		if form.is_valid():
			new_entry = form.save(commit=False)
			new_entry.topic = topic
			new_entry.save()
			return redirect('learning_logs: topic', topic_id=topic_id)  # 重定向

	# 显示空表单或指出表单数据无效
	context = {'topic': topic, 'form': form}
	return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
	"""编辑既有条目"""
	entry = Entry.objects.get(id=entry_id)
	topic = entry.topic
	if topic.owner != request.user:
		raise Http404

	if request.method != 'POST':
		# 初次请求：使用当前条目填充表单
		form = EntryForm(instance=entry)
	else:
		# POST提交的数据：对数据进行处理
		form = EntryForm(instance=entry, data=request.POST)
		if form.is_valid():
			form.save()
			return redirect('learning_logs:topic', topic_id=topic.id)

		context = {'entry': entry, 'topic': topic, 'form':form}
		return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
from django.shortcuts import render

from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
	"""注册新用户"""
	if request.method != 'POST':
		# 显示空的注册图表
		form = UserCreationForm()
	else:
		# 处理填写好的表单
		form = UserCreationForm(data=request.POST)

		if form.is_valid():
			new_user = form.save()
			# Log the user in and then redirect to home page.
			login(request, new_user)
			return redirect('learning_logs:index')

	# 展示空表或者指出表单无效
	context = {'form': form}
	return render(request, 'registration/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1,
    shrink-to-fit=no">
  <title>Learning Log（学习日志）</title>

  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}

</head>
<body>

  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

    <a class="navbar-brand" href="{% url 'learning_logs:index'%}">
        Learning Log（学习日志）</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'learning_logs:topics'%}">
              Topics（主题）</a></li>
      </ul>
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <span class="navbar-text">Hello, {{ user.username }}.</span>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
          </li>
          <li class="nav-item">
            <span>Already have an account?</span>
            <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
        {% endif %}
      </ul>
    </div>

  </nav>

  <main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>

</body>

</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a> </p>

  <p><a href="{% url 'leaning_logs:topic' topic.id % ">{{ topic }}</a></p>

  <p>Edit entry(编辑条目):</p>

  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button name="submit">Save changes(保存更改)</button>
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <div class="jumbotron">
    <h1 class="display-3">Track your learning.</h1>

    <p class="lead">Make your own Learning Log, and keep a list of the
        topics you're learning about. Whenever you learn something new
        about a topic, make an entry summarizing what you've learned.
        （做你自己的学习日志，把你正在学习的主题列一个清单。每当你对某个主题有新的了解时，
        记下你所学的东西。）</p>

    <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
        role="button">Register &raquo;</a>
  </div>
{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a> </p>

  <p>Add a new topic(添加一个新主题):</p>
  <form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button name="submit">Add entry(添加条目)</button>
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <p>Add a new topic(添加一个新主题):</p>

  <form action="{% url 'learning_logs:new_topic' %}" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button name="submit">Add topic(添加主题)</button>
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
  <h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}
  <p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry（添加新的条目）</a>
  </p>

  <ul>
  {% for entry in entries %}
    <div class="card mb-3">
      <h4 class="card-header">
        {{ entry.date_added|date:'M d, Y H:i' }}
        <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">
            edit entry</a></small>
      </h4>
      <div class="card-body">
        {{ entry.text|linebreaks }}
      </div>
    </div>
  {% empty %}
    <p>There are no entries for this topic yet.</p>
  {% endfor %}

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
<h1>Topics(主题)</h1>
{% endblock page_header %}

{% block content %}
<ul>
    {% for topic in topics %}
    <li><h3>
        <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
    </h3></li>
    {% empty %}
    <li><h3>No topics have been added yet.</h3></li>
    {% endfor %}
</ul>

<h3><a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a></h3>
{% endblock content %}